# Premiers pas en Python

In [142]:
import math
import pandas as pd
import numpy as np

## 1. Données de base

In [1]:
3 + 4

7

In [2]:
type(3)

int

In [4]:
nbAtome = 100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004
nbAtome

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004

In [5]:
nbAtome + 1

100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005

In [6]:
7 / 4

1.75

In [7]:
8 / 2

4.0

In [8]:
8 // 2

4

In [9]:
7 % 4

3

In [10]:
2**64

18446744073709551616

In [11]:
nbStudents = 35
nbStudents += 1
nbStudents

36

In [12]:
type(nbStudents)

int

In [13]:
pression = 10.754
pression

10.754

In [14]:
type(pression)

float

In [17]:
pression + 1.0, pression * 3, pression / 2

(11.754, 32.262, 5.377)

In [18]:
prix = 0.1
prix, prix *2, prix * 3

(0.1, 0.2, 0.30000000000000004)

In [23]:
infini = 1E308 * 10
infini, infini / infini

(inf, nan)

In [25]:
float('inf')

inf

In [19]:
prix > 1

False

In [20]:
prix * 10 == 1

True

In [26]:
prix is prix

True

In [27]:
today = 'Monday'
tomorrow = "Tuesday"
today, tomorrow

('Monday', 'Tuesday')

In [28]:
"aujourd'hui"

"aujourd'hui"

In [29]:
"aujourd'hui, je dis \"c'est la pause\""

'aujourd\'hui, je dis "c\'est la pause"'

In [30]:
type(today)

str

In [31]:
today.upper()

'MONDAY'

In [33]:
jours = "lundi,mardi,mercredi,jeudi".split(",")
jours

['lundi', 'mardi', 'mercredi', 'jeudi']

In [34]:
" - ".join(jours)

'lundi - mardi - mercredi - jeudi'

In [35]:
len(today)

6

In [36]:
today[0]

'M'

In [39]:
today[-1]

'y'

In [41]:
# today[10]
# IndexError: string index out of range

In [45]:
today[:1], today[1:4], today[4:]

('M', 'ond', 'ay')

In [46]:
today[:]

'Monday'

In [47]:
today[1:100], today[5:3]

('onday', '')

In [48]:
today[-3:]

'day'

In [49]:
today[5:3:-1]

'ya'

In [50]:
today[::-1]

'yadnoM'

In [51]:
# à eviter au maximum
today + ', ' + tomorrow  

'Monday, Tuesday'

In [54]:
f"{today} le bonbon est à {prix} cents"

'Monday le bonbon est à 0.1 cents'

In [55]:
"{} le bonbon est à {} cents".format(today, prix)

'Monday le bonbon est à 0.1 cents'

# Les conteneurs

In [56]:
ville_t = ("Pau", 64000, 77000)

In [58]:
ville_t[0]

'Pau'

In [60]:
nom, cp, pop = ville_t
print(nom, cp, pop)

Pau 64000 77000


In [61]:
jours[:2]

['lundi', 'mardi']

In [63]:
jours.append('vendredi')
jours

['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi']

In [65]:
jours.sort()
jours

['jeudi', 'lundi', 'mardi', 'mercredi', 'vendredi']

In [66]:
sorted(jours, reverse=True)

['vendredi', 'mercredi', 'mardi', 'lundi', 'jeudi']

In [69]:
ville_t.count?

In [70]:
list.extend?

In [77]:
ville_d = { 'nom': 'Pau', 'cp': 64000, 'pop':77000 }
ville_d

{'nom': 'Pau', 'cp': 64000, 'pop': 77000}

In [72]:
ville_d['nom']

'Pau'

In [78]:
ville_d['pop'] += 100
ville_d

{'nom': 'Pau', 'cp': 64000, 'pop': 77100}

In [79]:
ville_d['maire'] = 'François Bayrou'
ville_d

{'nom': 'Pau', 'cp': 64000, 'pop': 77100, 'maire': 'François Bayrou'}

In [80]:
del ville_d['maire']
ville_d

{'nom': 'Pau', 'cp': 64000, 'pop': 77100}

In [89]:
prix = 10.5
if prix < 1:
    print("pas cher")
elif prix < 5:
    print('ça va')
else:
    print('trop cher')
    print('je négocie')
print("J'achète dans tous les cas")

trop cher
je négocie
J'achète dans tous les cas


In [90]:
cpt = 10
while (cpt > 0):
    cpt -= 1
print("Fin", cpt)

Fin 0


In [91]:
for jour in jours:
    print(jour)

jeudi
lundi
mardi
mercredi
vendredi


In [92]:
data = [4.5, 6.7, 8.9, 10.3]

In [93]:
sum(x + 1 for x in data)

34.400000000000006

In [96]:
g = (x + 1 for x in data)
g

<generator object <genexpr> at 0x0000020427264048>

In [102]:
next(g)

StopIteration: 

In [110]:
sum(map(math.sqrt, data))

10.902404249880101

In [112]:
sum(x + 1 for x in data if x > 4)

34.400000000000006

In [113]:
sum(x + 1 for x in data if x > 30)

0

In [115]:
min(x + 1 for x in data if x > 30)

ValueError: min() arg is an empty sequence

In [118]:
def calcul(x, y=0):
    return math.sqrt(x) + y

In [121]:
calcul(4), calcul(4, 5), calcul(4, y=7)

(2.0, 7.0, 9.0)

In [125]:
def compute(*iterable):
    return sum(sum(it) for it in iterable)

In [126]:
compute(data, [1,2,3], (4,5,6))

51.400000000000006

In [131]:
for k in ville_d:
    print(k)

nom
cp
pop


In [132]:
for k in ville_d.keys():
    print(k)

nom
cp
pop


In [133]:
for v in ville_d.values():
    print(v)

Pau
64000
77100


In [134]:
for k,v in ville_d.items():
    print(k,v)

nom Pau
cp 64000
pop 77100


In [137]:
carre = [
    [ 8, 1, 6], 
    [3,5,7], 
    [4,9,2]]
carre

[[8, 1, 6], [3, 5, 7], [4, 9, 2]]

In [138]:
carre[0][2]

6

In [139]:
sum(carre[0])

15

In [140]:
[ carre[i][0] for i in range(len(carre)) ]

[8, 3, 4]

In [141]:
sum( carre[i][0] for i in range(len(carre)) )

15

In [144]:
carreN = np.array([
    [ 8, 1, 6], 
    [3,5,7], 
    [4,9,2]])
carreN

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [145]:
carreN[0]

array([8, 1, 6])

In [146]:
carreN[0,2]

6

In [147]:
carreN[:,0]

array([8, 3, 4])

In [148]:
carreN[0,:]

array([8, 1, 6])

In [149]:
sum(carreN[:,0])

15

In [151]:
carreN.sum()

45

In [152]:
np.sum(carreN)

45

In [153]:
carreN.sum(axis=0)

array([15, 15, 15])

In [155]:
carreN.diagonal().sum()

15

In [157]:
carreN[::-1].diagonal()

array([4, 5, 6])